/** Configurable account mapping roles — no hardcoded account codes in posting logic. */
export const ACCOUNT_ROLES = {
  CASH: "CASH",
  BANK: "BANK",
  INVENTORY: "INVENTORY",
  ACCOUNTS_RECEIVABLE: "ACCOUNTS_RECEIVABLE",
  ACCOUNTS_PAYABLE: "ACCOUNTS_PAYABLE",
  SALES_REVENUE: "SALES_REVENUE",
  SALES_RETURN: "SALES_RETURN",
  TAX_PAYABLE: "TAX_PAYABLE",
  FREIGHT_INCOME: "FREIGHT_INCOME",
  PURCHASE_ACCOUNT: "PURCHASE_ACCOUNT",
  PURCHASE_RETURN: "PURCHASE_RETURN",
  COGS: "COGS",
  INVENTORY_ADJUSTMENT_GAIN: "INVENTORY_ADJUSTMENT_GAIN",
  INVENTORY_ADJUSTMENT_LOSS: "INVENTORY_ADJUSTMENT_LOSS",
  CLAIMS_EXPENSE: "CLAIMS_EXPENSE",
  RECOVERY_ACCOUNT: "RECOVERY_ACCOUNT",
  EQUITY: "EQUITY",
};

/** Default chart codes used only when seeding mappings — not in posting logic. */
export const DEFAULT_ROLE_ACCOUNT_CODES = {
  [ACCOUNT_ROLES.CASH]: "1100",
  [ACCOUNT_ROLES.BANK]: "1200",
  [ACCOUNT_ROLES.INVENTORY]: "1300",
  [ACCOUNT_ROLES.ACCOUNTS_RECEIVABLE]: "1400",
  [ACCOUNT_ROLES.ACCOUNTS_PAYABLE]: "2100",
  [ACCOUNT_ROLES.TAX_PAYABLE]: "2200",
  [ACCOUNT_ROLES.SALES_REVENUE]: "4000",
  [ACCOUNT_ROLES.SALES_RETURN]: "4000",
  [ACCOUNT_ROLES.FREIGHT_INCOME]: "4100",
  [ACCOUNT_ROLES.PURCHASE_ACCOUNT]: "1300",
  [ACCOUNT_ROLES.PURCHASE_RETURN]: "1300",
  [ACCOUNT_ROLES.COGS]: "5000",
  [ACCOUNT_ROLES.INVENTORY_ADJUSTMENT_GAIN]: "5200",
  [ACCOUNT_ROLES.INVENTORY_ADJUSTMENT_LOSS]: "5210",
  [ACCOUNT_ROLES.CLAIMS_EXPENSE]: "5100",
  [ACCOUNT_ROLES.RECOVERY_ACCOUNT]: "1100",
  [ACCOUNT_ROLES.EQUITY]: "3000",
};

export const SOURCE_DOCUMENT_TYPES = {
  SALES_INVOICE: "SALES_INVOICE",
  SALES_RETURN: "SALES_RETURN",
  PURCHASE_INVOICE: "PURCHASE_INVOICE",
  PURCHASE_RETURN: "PURCHASE_RETURN",
  RECOVERY: "RECOVERY",
  VENDOR_PAYMENT: "VENDOR_PAYMENT",
  CLAIM: "CLAIM",
  STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT",
  VOUCHER: "VOUCHER",
};
