import { contextBridge, ipcRenderer } from "electron";

function masterApi(entity) {
  return {
    list: () => ipcRenderer.invoke(`masters:${entity}:list`),
    save: (data) => ipcRenderer.invoke(`masters:${entity}:save`, data),
    delete: (id) => ipcRenderer.invoke(`masters:${entity}:delete`, id),
  };
}

contextBridge.exposeInMainWorld("api", {
  auth: {
    login: (credentials) => ipcRenderer.invoke("auth:login", credentials),
    validate: (token) => ipcRenderer.invoke("auth:validate", token),
    logout: (token) => ipcRenderer.invoke("auth:logout", token),
  },
  company: {
    list: () => ipcRenderer.invoke("company:list"),
    create: (data) => ipcRenderer.invoke("company:create", data),
    select: (data) => ipcRenderer.invoke("company:select", data),
  },
  masters: {
    lookups: () => ipcRenderer.invoke("masters:lookups"),
    units: masterApi("units"),
    warehouses: masterApi("warehouses"),
    accounts: masterApi("accounts"),
    routes: masterApi("routes"),
    salesmen: masterApi("salesmen"),
    products: masterApi("products"),
    customers: masterApi("customers"),
    vendors: masterApi("vendors"),
  },
  purchase: {
    lookups: () => ipcRenderer.invoke("purchase:lookups"),
    listInvoices: () => ipcRenderer.invoke("purchase:invoices:list"),
    getInvoice: (id) => ipcRenderer.invoke("purchase:invoices:get", id),
    saveInvoice: (data) => ipcRenderer.invoke("purchase:invoices:save", data),
    previewTotals: (data) => ipcRenderer.invoke("purchase:invoices:preview", data),
    listReturns: () => ipcRenderer.invoke("purchase:returns:list"),
    saveReturn: (data) => ipcRenderer.invoke("purchase:returns:save", data),
  },
  sales: {
    lookups: () => ipcRenderer.invoke("sales:lookups"),
    listQuotations: () => ipcRenderer.invoke("sales:quotations:list"),
    saveQuotation: (data) => ipcRenderer.invoke("sales:quotations:save", data),
    convertQuotation: (id) => ipcRenderer.invoke("sales:quotations:convert", id),
    listInvoices: () => ipcRenderer.invoke("sales:invoices:list"),
    saveInvoice: (data) => ipcRenderer.invoke("sales:invoices:save", data),
    listPendingDeliveries: () => ipcRenderer.invoke("sales:invoices:pending"),
    listRecoveries: () => ipcRenderer.invoke("sales:recoveries:list"),
    saveRecovery: (data) => ipcRenderer.invoke("sales:recoveries:save", data),
    getOutstandingInvoices: (customerId) =>
      ipcRenderer.invoke("sales:recoveries:outstanding", customerId),
    listLoadSlips: () => ipcRenderer.invoke("sales:loadslips:list"),
    saveLoadSlip: (data) => ipcRenderer.invoke("sales:loadslips:save", data),
    deliverLoadSlip: (id) => ipcRenderer.invoke("sales:loadslips:deliver", id),
    listDeliveryMen: () => ipcRenderer.invoke("sales:deliverymen:list"),
    saveDeliveryMan: (data) => ipcRenderer.invoke("sales:deliverymen:save", data),
    listReturns: () => ipcRenderer.invoke("sales:returns:list"),
    saveReturn: (data) => ipcRenderer.invoke("sales:returns:save", data),
    getReturnInvoice: (id) => ipcRenderer.invoke("sales:returns:invoice", id),
  },
  claims: {
    lookups: () => ipcRenderer.invoke("claims:lookups"),
    list: (filters) => ipcRenderer.invoke("claims:list", filters),
    save: (data) => ipcRenderer.invoke("claims:save", data),
    updateStatus: (data) => ipcRenderer.invoke("claims:status", data),
    settle: (data) => ipcRenderer.invoke("claims:settle", data),
    report: (filters) => ipcRenderer.invoke("claims:report", filters),
  },
  stock: {
    list: () => ipcRenderer.invoke("stock:list"),
  },
  inventory: {
    lookups: () => ipcRenderer.invoke("inventory:lookups"),
    getStockTakeSheet: (warehouseId) => ipcRenderer.invoke("inventory:stocktake:sheet", warehouseId),
    finalizeStockTake: (data) => ipcRenderer.invoke("inventory:stocktake:finalize", data),
    saveOpeningStock: (data) => ipcRenderer.invoke("inventory:opening:save", data),
    saveAdjustment: (data) => ipcRenderer.invoke("inventory:adjustments:save", data),
    listAdjustments: () => ipcRenderer.invoke("inventory:adjustments:list"),
    saveTransfer: (data) => ipcRenderer.invoke("inventory:transfers:save", data),
    listTransfers: () => ipcRenderer.invoke("inventory:transfers:list"),
    lowStockReport: () => ipcRenderer.invoke("inventory:reports:lowstock"),
    expiryReport: () => ipcRenderer.invoke("inventory:reports:expiry"),
  },
  accounting: {
    lookups: () => ipcRenderer.invoke("accounting:lookups"),
    listVouchers: (filters) => ipcRenderer.invoke("accounting:vouchers:list", filters),
    saveVoucher: (data) => ipcRenderer.invoke("accounting:vouchers:save", data),
    buildQuickLines: (data) => ipcRenderer.invoke("accounting:vouchers:quicklines", data),
    listJournal: (filters) => ipcRenderer.invoke("accounting:journal:list", filters),
    trialBalance: (filters) => ipcRenderer.invoke("accounting:trialbalance", filters),
    cashbook: (filters) => ipcRenderer.invoke("accounting:cashbook", filters),
    accountLedger: (filters) => ipcRenderer.invoke("accounting:ledger", filters),
    dailyCash: (filters) => ipcRenderer.invoke("accounting:dailycash", filters),
    profitLoss: (filters) => ipcRenderer.invoke("accounting:profitloss", filters),
  },
  reports: {
    aging: (filters) => ipcRenderer.invoke("reports:aging", filters),
    balanceSheet: (filters) => ipcRenderer.invoke("reports:balancesheet", filters),
    incomeStatement: (filters) => ipcRenderer.invoke("reports:incomestatement", filters),
    customerOutstanding: () => ipcRenderer.invoke("reports:customeroutstanding"),
    customerSales: (filters) => ipcRenderer.invoke("reports:customersales", filters),
    recovery: (filters) => ipcRenderer.invoke("reports:recovery", filters),
    salesmen: (filters) => ipcRenderer.invoke("reports:salesmen", filters),
    productSales: (filters) => ipcRenderer.invoke("reports:productsales", filters),
    purchases: (filters) => ipcRenderer.invoke("reports:purchases", filters),
    stockValuation: () => ipcRenderer.invoke("reports:stockvaluation"),
    commission: (filters) => ipcRenderer.invoke("reports:commission", filters),
  },
  tools: {
    backup: () => ipcRenderer.invoke("tools:backup"),
    backupLocal: () => ipcRenderer.invoke("tools:backup:local"),
    listLocalBackups: () => ipcRenderer.invoke("tools:backup:list"),
    restore: () => ipcRenderer.invoke("tools:restore"),
    exportEntities: () => ipcRenderer.invoke("tools:export:entities"),
    exportCsv: (entity) => ipcRenderer.invoke("tools:export:csv", entity),
    importCsv: (entity) => ipcRenderer.invoke("tools:import:csv", entity),
    printHtml: (html) => ipcRenderer.invoke("tools:printHtml", html),
  },
});
